// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl2EEplr-Cs5f5oiglfetLNQkwLlEBzaY',
    appId: '1:1016646892735:web:b1bf49116a170d7fd51a0a',
    messagingSenderId: '1016646892735',
    projectId: 'applearnjava',
    authDomain: 'applearnjava.firebaseapp.com',
    storageBucket: 'applearnjava.firebasestorage.app',
    measurementId: 'G-NWSWJPSG45',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKRSqa1yPPOYwO4sHeRtA-3n00PCIm6OI',
    appId: '1:1016646892735:android:66a502721371d955d51a0a',
    messagingSenderId: '1016646892735',
    projectId: 'applearnjava',
    storageBucket: 'applearnjava.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDjR-TCTfoTCBx01PyI06AJNuZP_dlcZA',
    appId: '1:1016646892735:ios:735665855cc19033d51a0a',
    messagingSenderId: '1016646892735',
    projectId: 'applearnjava',
    storageBucket: 'applearnjava.firebasestorage.app',
    iosBundleId: 'com.example.learnJava',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDjR-TCTfoTCBx01PyI06AJNuZP_dlcZA',
    appId: '1:1016646892735:ios:735665855cc19033d51a0a',
    messagingSenderId: '1016646892735',
    projectId: 'applearnjava',
    storageBucket: 'applearnjava.firebasestorage.app',
    iosBundleId: 'com.example.learnJava',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl2EEplr-Cs5f5oiglfetLNQkwLlEBzaY',
    appId: '1:1016646892735:web:a712a01175d43ab5d51a0a',
    messagingSenderId: '1016646892735',
    projectId: 'applearnjava',
    authDomain: 'applearnjava.firebaseapp.com',
    storageBucket: 'applearnjava.firebasestorage.app',
    measurementId: 'G-D2FHTR223X',
  );

}